---
# ansible hosts 
# yaml format
all:
    hosts:
        DeployHostDefault:
            ansible_host: 45.33.46.26
            ansible_user: root
            ansible_port: 22
            ansible_python_interpreter: /usr/bin/python3
            
        DeployHost:
            ansible_host: 45.33.46.26
            ansible_user: deploy
            ansible_port: 774
            ansible_ssh_private_key_file: keys/deploy_id
            ansible_python_interpreter: /usr/bin/python3


        things:
            thing1_fresh:
                ansible_host: 172.104.122.51
                ansible_user: root
                ansible_python_interpreter: /usr/bin/python3
                ansible_ssh_extra_args: "-o StrictHostKeyChecking=no"

            thing1:
                ansible_host: 172.104.122.51
                ansible_user: deploy
                ansible_ssh_private_key_file: keys/deploy_id
                ansible_python_interpreter: /usr/bin/python3
...