---
- hosts: fresh_things
  become: yes
  tasks:

    - name: "Talk to host"
      ping: 
      
    - name: "Add wheel group"
      group:
        name: wheel
        state: present
        
    - name: "Adjust wheel group"
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^%wheel'
        line: '%wheel ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'
        

# TESTING PORPOISE (
# There is only one type of "testing porpoise" ergo "porpoise" is the correct plural)
    - name: "Add self"
      user: 
        name: samuel
        comment: samuel.emmett.bray@gmail.com
        append: yes
        create_home: yes
        groups: wheel
      
    - name: "Add ssh key"
      authorized_key:
        user: samuel
        path: /home/samuel/.ssh/authorized_keys
        state: present
        key: "{{ lookup('file', '/home/samuel/.ssh/id_rsa.pub') }}"

# END TESTING PORPOISE 

    - name: "Update packages"
      apt:
        autoclean: yes
        autoremove: yes
        update_cache: yes
        cache_valid_time: 36000
        force_apt_get: yes
        state: latest
        name: "*"
      register: task_result

    - name: "Reboot if changed"
      shell: "sleep 5 && reboot"
      async: 1
      poll: 0
      when: task_result is changed

    - name: "Wait for connection if reboot was triggered"
      wait_for_connection:
        connect_timeout: 5
        sleep: 5
        delay: 20
        timeout: 300
      when: task_result is changed

- hosts: things
  become: yes
  tasks: 
    - name: "Validate"
      ping:

    - name: "Setup node install"
      shell: "curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -" 
      args:
        warn: false
      register: nodeSetup

    - name: "Setup yarn install"
      shell: 'curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add - && echo "deb https://dl.yarnkpg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list'
      args:
        warn: false
      register: yarnSetup

    - name: "Install packages"
      apt:
        autoclean: yes
        autoremove: yes
        update_cache: yes
        cache_valid_time: 36000
        force_apt_get: yes
        state: latest
        name: "{{ item }}"
      with_items:
        - git
        - curl
        - zlib1g-dev 
        - build-essential
        - libssl-dev
        - libreadline-dev
        - libyaml-dev
        - libsqlite3-dev
        - sqlite3
        - libxml2-dev
        - libxslt1-dev
        - libcurl4-openssl-dev
        - software-properties-common
        - libffi-dev
        - nodejs
        - yarn
        - libgdbm-dev
        - libncurses5-dev
        - automake
        - libtool
        - bison
        - flex
        - nginx
    
    - name: "Make sure we didn't break anything"
      ping:

    # OK Setup SSH

    - name: "Setup SSH"

    
...
